### ISSUE TITLE
Experiments on simulation (LIBERO)

### ISSUE THREAD

**Issue by Ricky-Zhu** [UT-Austin-RPL/GROOT#3]
Hi, thanks for making this interesting work. Just wondering would you release the codebase for the simulation experiments?

Thank you!

**Comment by zhuyifengzju** [comment]
Hi, I refactored the codebase for real robot experiments only, and it is not in my bandwidth to refactor the simulation code at the moment. We will have some relevant works that come with simulation environments.

**Comment by Ricky-Zhu** [comment]
thank you for the replying.

**Comment by ahadjawaid** [comment]
For the LIBERO dataset that contained the RGB-D images did you generate a new dataset? Since the publicly available LIBERO dataset from what I saw only had RGB image.
